# Generated by Django 2.1.5 on 2019-03-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0003_auto_20190314_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='id',
        ),
        migrations.AlterField(
            model_name='building',
            name='b_num',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
