# Generated by Django 2.1.5 on 2019-02-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0003_demo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo',
            options={'managed': False},
        ),
    ]
