# Generated by Django 2.1.5 on 2019-03-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0004_auto_20190314_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='s_type',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
