# Generated by Django 2.1.5 on 2019-02-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0004_auto_20190219_2247'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='demo',
            table='Demo',
        ),
    ]
