# Generated by Django 2.1.5 on 2019-03-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0005_auto_20190219_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('usage', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('building', models.IntegerField()),
                ('util', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'export_demo',
                'managed': False,
            },
        ),
    ]
