# Generated by Django 2.1.5 on 2019-03-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0006_exportbuilding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
    ]
