# Generated by Django 2.1.5 on 2019-03-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0007_buildingsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
