# Generated by Django 2.1.5 on 2019-03-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0008_loginform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'edashboard_user',
                'managed': False,
            },
        ),
    ]
