# Generated by Django 2.1.5 on 2019-03-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0009_users'),
        ('edashboard', '0005_auto_20190314_1634'),
    ]

    operations = [
    ]
