# Generated by Django 2.1.5 on 2019-03-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0005_auto_20190314_1634'),
        ('edashboard', '0010_auto_20190314_1925'),
    ]

    operations = [
    ]
