# Generated by Django 2.1.5 on 2019-03-15 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0010_merge_20190314_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginForm',
        ),
    ]
