# Generated by Django 2.1.5 on 2019-03-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0012_auto_20190314_1827'),
        ('edashboard', '0010_auto_20190314_1925'),
    ]

    operations = [
    ]
