# Generated by Django 2.1.5 on 2019-03-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0011_merge_20190315_1058'),
        ('edashboard', '0013_merge_20190315_1127'),
    ]

    operations = [
    ]
