# Generated by Django 2.1.5 on 2019-04-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0013_merge_20190315_1127'),
        ('edashboard', '0011_merge_20190315_1058'),
    ]

    operations = [
    ]
