# Generated by Django 2.1.5 on 2019-04-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0014_merge_20190423_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='BuildingSearch',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='Low Level User', max_length=100),
        ),
    ]
