# Generated by Django 2.1.5 on 2019-04-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0017_remove_sensortype_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='unit',
            field=models.CharField(default='?', max_length=200),
        ),
    ]
