# Generated by Django 2.1.5 on 2019-05-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0021_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='c_type',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
