# Generated by Django 2.1.5 on 2019-03-15 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0011_delete_loginform'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='b_num',
            field=models.CharField(max_length=10),
        ),
    ]
