# Generated by Django 2.1.5 on 2019-04-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0016_sensortype_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensortype',
            name='desc',
        ),
    ]
