# Generated by Django 2.1.5 on 2019-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edashboard', '0019_sensor_s_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='s_log',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
